# This file was generated by GoReleaser. DO NOT EDIT.
cask "cutterd" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "dc0216cb4089ed70e8e2403eb2871d49e7739b547c393065ac65fe929207345d"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c90860e77734bce954f24214077d6bd860a92fb3f38b730d4b9f8b68527bee65"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29ebdb710438e0df4f4cbaac338e2c28697ce4303f1586b61184c36206e9dbb8"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "22eeb8c6d7ef5fc2611d8819cb386a82ee2f4679e6e5ccdf41e637ea9081b820"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cutterd"
  desc "BangerVision on-site video cutting service (cutterd)"
  homepage "https://github.com/cubera-ch/bangervision-service"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "cutterd"

  # No zap stanza required

  caveats <<~EOS
    cutterd is installed. To run it as a boot/restart daemon on a Mac mini,
    install the launchd plist bundled in the release archive:
      https://github.com/cubera-ch/bangervision-service#deploy-on-the-mac-mini-launchd
  EOS
end
