# This file was generated by GoReleaser. DO NOT EDIT.
cask "cutterd" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "4ff71dc003bc0319dc82af98dc8222be4bd6d9ebac9d51e7a0a5074ad4780b79"
      url "https://github.com/cubera-ch/bangervision-service/releases/download/v#{version}/cutterd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f453f23e990d9c45b8eb0351bf098a33908cbe5f98caf44f549799d014ef81b"
      url "https://github.com/cubera-ch/bangervision-service/releases/download/v#{version}/cutterd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01415d237b45b0a5ecc68be3addb4bedeb97fc451c85647e895848c910e25554"
      url "https://github.com/cubera-ch/bangervision-service/releases/download/v#{version}/cutterd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f904686b2a9cfe37856fdca38d982f073c3b7752498045c9fec7b9cd5929aa3"
      url "https://github.com/cubera-ch/bangervision-service/releases/download/v#{version}/cutterd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cutterd"
  desc "BangerVision on-site video cutting service (cutterd)"
  homepage "https://github.com/cubera-ch/bangervision-service"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "cutterd"

  # No zap stanza required

  caveats <<~EOS
    cutterd is installed. To run it as a boot/restart daemon on a Mac mini,
    install the launchd plist bundled in the release archive:
      https://github.com/cubera-ch/bangervision-service#deploy-on-the-mac-mini-launchd
  EOS
end
