# This file was generated by GoReleaser. DO NOT EDIT.
cask "cutterd" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "213c8e98e701eaaf645f04155537455b21d9f48ce47fca64c9c42ce920fe390c"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "199d7824d22b4a0f9d146d318c548177a79a264bbab2713b39b612f326f6e5ce"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "85d9c88a3c48f55f26b43d39b590a2724886de039802c4d281fba0d01e508ffc"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5b593986217ce2e978d268617b86c6630dd41a6047e8dc98526708fe1fd529e"
      url "https://github.com/cubera-ch/homebrew-tap/releases/download/v#{version}/cutterd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cutterd"
  desc "BangerVision on-site video cutting service (cutterd)"
  homepage "https://github.com/cubera-ch/bangervision-service"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "cutterd"

  # No zap stanza required

  caveats <<~EOS
    cutterd is installed. To run it as a boot/restart daemon on a Mac mini,
    install the launchd plist bundled in the release archive:
      https://github.com/cubera-ch/bangervision-service#deploy-on-the-mac-mini-launchd
  EOS
end
